### ISSUE TITLE
Running commentary

### ISSUE THREAD

**Issue by resistorsoftware** [baoagency/polaris_view_components#315]
Throwing down a new App and running into a few small things. 
1. I notice Polaris has a range selector, but PVC does not. I guess I need to add that to this repo? OK
2. I was setting up a horizontal stack and made some bonehead mistakes. To boot

`block_align does not work with a string, like "center", but only took a symbol, like block_align: :center`

`gap only takes a string, not an integer, like gap: 4 has to be gap: "4"`

None of this is very interesting, but it is kinda interesting where the use becomes edgy!

Also, https://polarisviewcomponents.org/lookbook/inspect/horizontal_stack/align blows out with a
`ViewComponent::MissingPreviewTemplateError`

Thanks for PVC nonetheless. I hope it keeps on trucking!

**Comment by kirillplatonov** [comment]
> I notice Polaris has a range selector, but PVC does not. I guess I need to add that to this repo? OK
Yeah, we don't have RangeSlider component. Feel free to contribute.

> None of this is very interesting, but it is kinda interesting where the use becomes edgy!
It can be improved in cases like `block_align`. But for `gap` it's much worse. Potential values include `025` and `05` so can't be easily converted from numeric format. Influence of Polaris naming decisions 🤷‍♂️

> Also, https://polarisviewcomponents.org/lookbook/inspect/horizontal_stack/align blows out with a
ViewComponent::MissingPreviewTemplateError
Thanks, fixed by removing missing preview.
